parameters:
- name: syncGitHub
  type: boolean
  default: true

stages:
- stage: GitHub
  displayName: Mirror to GitHub
  pool:
    name: '$[variables.buildPoolName]'
    vmImage: '$[variables.buildPoolWindowsVSVm]'
  jobs:
  - job: GitHub
    displayName: Mirror to GitHub
    steps:
    - script:
        echo '$(Build.Repository.Uri)'
        echo '$(gitHubRepoUrl)'
        echo '$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_git/$(Build.Repository.Name)'
    - task: swellaby.mirror-git-repository.mirror-git-repository-vsts-task.mirror-git-repository-vsts-task@1
      displayName: 'Mirror Git Repository'
      inputs:
        sourceGitRepositoryUri: '$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_git/$(Build.Repository.Name)'
        sourceGitRepositoryPersonalAccessToken: $(system.accesstoken)
        destinationGitRepositoryUri: '$(gitHubRepoUrl)'
        destinationGitRepositoryPersonalAccessToken: '$(gitHubRepoPat)'
      env:
        SYSTEM_ACCESSTOKEN: $(system.accesstoken)
#    - task: gitmirror@0
#      displayName: "Mirror Repository to GitHub"
#      inputs:
#        GitRepoUrl: '$(gitHubRepoUrl)'
#      env:
#        SYSTEM_ACCESSTOKEN: $(system.accesstoken)